FROM rocker/verse:4.2.0
RUN apt-get update -y && apt-get install -y  make pandoc libicu-dev  perl  make zlib1g-dev pandoc libpng-dev libjpeg-dev libicu-dev  make libcurl4-openssl-dev  make cmake zlib1g-dev libicu-dev  libicu-dev  make  make cmake libicu-dev  git libssl-dev libcurl4-openssl-dev  libcurl4-openssl-dev libssl-dev  zlib1g-dev  make zlib1g-dev  git libgit2-dev libssl-dev libcurl4-openssl-dev  libfontconfig1-dev libfreetype6-dev  libfontconfig1-dev libfreetype6-dev libglpk-dev libgmp3-dev libxml2-dev  git  git libxml2-dev make pandoc libgit2-dev libssl-dev libicu-dev libcurl4-openssl-dev zlib1g-dev  libglpk-dev libgmp3-dev libxml2-dev  libssl-dev libcurl4-openssl-dev  libjpeg-dev  pandoc libicu-dev  libpng-dev libjpeg-dev  make cmake  libssl-dev  make zlib1g-dev pandoc libssl-dev libicu-dev libcurl4-openssl-dev  libpng-dev  make libglpk-dev libgmp3-dev libxml2-dev zlib1g-dev pandoc libpng-dev libjpeg-dev libicu-dev  git make libgit2-dev libssl-dev libcurl4-openssl-dev && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /usr/local/lib/R/etc/ /usr/lib/R/etc/
RUN echo "options(renv.config.pak.enabled = TRUE, repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl', Ncpus = 4)" | tee /usr/local/lib/R/etc/Rprofile.site | tee /usr/lib/R/etc/Rprofile.site
RUN R -e 'install.packages(c("renv","remotes"))'
COPY renv.lock.prod renv.lock
RUN R -e 'renv::restore()'
