#' @title Fill missing values
#' @description Fill missing values.
#' @param df processed data generated by formatData function. It has a ID column, and all the rests are peak area info;
#'  Each row is one feature, and each column is one sample.
#' @param method Missing value filling method.
#' @return a data frame without missing value.
#' @noRd
#' @examples
#' df <- cbind.data.frame(ID = c(1, 2), S1 = c(14, 3), S2 = c(15, NA), S3 = c(NA, 5))
#' rownames(df) <- c("M1", "M2")
#' fillNA(df, method = "KNN")

fillNA <- function(df, method = "1"){
  id <- df$ID
  df <- subset(df, select = -ID)
  df2 <- switch(method,
                "1" = replace(df, is.na(df), 1),
                "HM" = as.data.frame(t(apply(df, 1, function(x) replace(x, is.na(x), 0.2 * min(x, na.rm = TRUE))))),
                "KNN" = kNNMissing(df),
                "Mean" = as.data.frame(t(apply(df, 1, function(x) replace(x, is.na(x), mean(x, na.rm = TRUE))))),
                "Median" = as.data.frame(t(apply(df, 1, function(x) replace(x, is.na(x), median(x, na.rm = TRUE)))))
                )

  df2[df2 == 0] <- 1
  df2$ID <- id
  data.table::setcolorder(df2, neworder = "ID")
  return(df2)
}


kNNMissing <- function(x) {
  df <- VIM::kNN(t(x), imp_var = F)
  rownames(df) <- colnames(x)
  df2 <- t(df)
  df2 <- as.data.frame(df2)
  rownames(df2) <- NULL
  return(df2)
}
