#' @title Plot TIC
#' @description Plot peak area as box plot.
#' @param df processed data frame generated by formatData function. It has a ID column, and all the rests are peak area info;
#'  Each row is one feature, and each column is one sample.
#' @param Group sample group information
#' @param method which method is used to make boxplot, default is "fast".
#' @importFrom ggplot2 aes element_blank
#' @return boxplot
#' @export
#' @noRd
#' @examples
#' df <- data.frame(
#' ID = c("A", "B", "C", "D", "E"),
#' p1 = c(99, 90, 86, 88, 95),
#' p2 = c(33, 28, 31, 39, 34),
#' p3 = c(30, 28, 24, 24, 28)
#' )
#' Group <- c("X", "Y", "Z")
#' showTIC(df, Group)

showTIC <- function(df, Group = NULL){
  #(1) Format data -------------------------------------------------------------
  df$ID <- NULL
  quantiles <- t(apply(df, 2, quantile, probs = c(0.05, 0.25, 0.5, 0.75, 0.95)))
  if(is.null(Group)){Group = rownames(quantiles)}
  df <- cbind.data.frame(Group = Group, Sample = rownames(quantiles), quantiles)
  #(2) Plot --------------------------------------------------------------------
  ggplot2::ggplot(df, aes(x = Sample, ymin = `5%`, lower =`25%`, middle = `50%`, upper = `75%`, ymax = `95%`, fill = Group)) +
    ggplot2::geom_boxplot(stat = "identity", alpha = 0.7) +
    ggplot2::ylab("Peak Area") +
    ggplot2::theme_bw() +
    ggplot2::theme(axis.text.x = element_blank())
}
