#' @title Fill missing values
#' @description Fill missing values.
#' @param df processed data frame generated by formatData function. It has a ID column, and all the rests are peak area info;
#'  Each row is one feature, and each column is one sample.
#' @param method Missing value filling method.
#' @return a data frame without missing value.
#' @noRd
#' @examples
#' df <- cbind.data.frame(ID = c(1, 2), S1 = c(14, 3), S2 = c(15, NA), S3 = c(NA, 5))
#' rownames(df) <- c("M1", "M2")
#' fillNA(df, method = "KNN")

fillNA <- function(df, method = "1"){
  id <- df$ID
  df <- subset(df, select = -ID)
  df <- switch(method,
                "1" = replace(df, is.na(df), 1),
                "HM" = as.data.frame(t(apply(df, 1, function(x) replace(x, is.na(x), 0.2 * min(x, na.rm = TRUE))))),
                "KNN" = kNNMissing(df),
                "Mean" = as.data.frame(t(apply(df, 1, function(x) replace(x, is.na(x), mean(x, na.rm = TRUE))))),
                "Median" = as.data.frame(t(apply(df, 1, function(x) replace(x, is.na(x), median(x, na.rm = TRUE)))))
                )
  df$ID <- id
  data.table::setcolorder(df, neworder = "ID")
  return(df)
}

#' @title k-Nearest Neighbour Imputation
#' @description k-Nearest Neighbour imputation using VIM package
#' @param x dataframe, row is feature, column is sample
#' @importFrom VIM kNN
#' @return a dataframe will filled missing value
#' @export
#' @noRd

kNNMissing <- function(x) {
  df <- VIM::kNN(t(x), imp_var = FALSE)
  rownames(df) <- colnames(x)
  df <- t(df)
  df <- as.data.frame(df)
  return(df)
}

